export default function () {
    return [
        {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: 'https://static.pleer.ru/i/p/432558/432558m.jpg',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: 'https://static.pleer.ru/i/p/432558/432558m.jpg',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: 'https://static.pleer.ru/i/p/432558/432558m.jpg',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: 'https://static.pleer.ru/i/p/432558/432558m.jpg',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: 'https://static.pleer.ru/i/p/432558/432558m.jpg',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: 'https://static.pleer.ru/i/p/432558/432558m.jpg',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: 'https://static.pleer.ru/i/p/432558/432558m.jpg',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: 'https://static.pleer.ru/i/p/432558/432558m.jpg',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'RX 570 Sapphire Nitro +',
            price: '0.03',
            currency: 'BTC',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: 'https://static.pleer.ru/i/p/432558/432558m.jpg',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: 'https://static.pleer.ru/i/p/432558/432558m.jpg',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        }, {
            offerid: '1',
            area: 'м. Бабушкинская',
            name: 'блок питания Chieftec 750',
            price: '2400',
            currency: 'RUB',
            image: '../../Images/photo.png',
        },   
    ]
}